# Generated by Django 4.0.6 on 2024-10-25 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.IntegerField()),
                ('pending_completion', models.BooleanField(default=True)),
                ('sp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.serviceprovider')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.client')),
            ],
        ),
    ]
