# Generated by Django 4.0.6 on 2024-10-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_servicehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicehistory',
            old_name='u_id',
            new_name='client_id',
        ),
    ]
