# Generated by Django 4.0.6 on 2024-10-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_rename_u_id_servicehistory_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicehistory',
            old_name='client_id',
            new_name='client',
        ),
    ]
